# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai-class',
                'doc_host': 'https://myksmith.github.io',
                'git_url': 'https://github.com/myksmith/fastai-class',
                'lib_path': 'fastai_class'},
  'syms': {'fastai_class.core': {'fastai_class.core.foo': ('core.html#foo', 'fastai_class/core.py')}}}
